# Generated by Django 3.0.6 on 2020-05-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
